# Generated by Django 5.2.1 on 2025-05-28 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2025, 5, 28, 19, 32, 28, 748993, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
